In [1]:
from IPython.core.display import HTML, display
from string import Template
import pandas as pd
import json, random

In [2]:
import pandas as pd
pd.__version__

'0.25.3'

In [3]:
from nltk.corpus import brown


In [2]:
words = brown.words()[:1000]
len(words)

1000

In [7]:
print(" ".join(words))

The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place . The jury further said in term-end presentments that the City Executive Committee , which had over-all charge of the election , `` deserves the praise and thanks of the City of Atlanta '' for the manner in which the election was conducted . The September-October term jury had been charged by Fulton Superior Court Judge Durwood Pye to investigate reports of possible `` irregularities '' in the hard-fought primary which was won by Mayor-nominate Ivan Allen Jr. . `` Only a relative handful of such reports was received '' , the jury said , `` considering the widespread interest in the election , the number of voters and the size of this city '' . The jury said it did find that many of Georgia's registration and election laws `` are outmoded or inadequate and often ambiguous '' . It recommended that Fulton legislators act `` to have th

In [109]:
sents = brown.sents()[:20]

In [ ]:
sents

In [5]:
import nltk
from nltk.tokenize import word_tokenize
import spacy
import re, string

In [6]:
nltk.download('stopwords')
from nltk.corpus import stopwords
STOPWORDS = stopwords.words('english')

[nltk_data] Downloading package stopwords to /home/sultan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [7]:
def clean_text(word):
    '''Make text lowercase, remove square brackets, remove punctuation and remove words containing numbers.'''
    word = word.lower()
    word = re.sub(r'[\[\]\(\)\{\}]', '', word)
    word = re.sub(r'[%s]' % re.escape(string.punctuation), '', word)
    word = re.sub(r'\w*\d\w*', '', word)
    
    # text = word_tokenize(text)
    # Remove a sentence if it is only one word long
    return word if word not in STOPWORDS else None

In [8]:
nlp = spacy.load('en')


In [76]:
from sklearn.feature_extraction.text import CountVectorizer
docs = ['this this this book',
        'this cat good',
        'cat good shit']
count_model = CountVectorizer(ngram_range=(1,1)) # default unigram model
X = count_model.fit_transform(docs)
# X[X > 0] = 1 # run this line if you don't want extra within-text cooccurence (see below)
Xc = (X.T * X) # this is co-occurrence matrix in sparse csr format
Xc.setdiag(0) # sometimes you want to fill same word cooccurence to 0
print(Xc.todense()) # print out matrix in dense format
print(count_model.get_feature_names())

[[0 0 0 0 3]
 [0 0 2 1 1]
 [0 2 0 1 1]
 [0 1 1 0 0]
 [3 1 1 0 0]]
['book', 'cat', 'good', 'shit', 'this']


In [87]:
type(Xc.todense())

numpy.matrix

In [90]:
import numpy as np

In [94]:
l = np.array(Xc.todense()).tolist()

In [95]:
l

[[0, 0, 0, 0, 3],
 [0, 0, 2, 1, 1],
 [0, 2, 0, 1, 1],
 [0, 1, 1, 0, 0],
 [3, 1, 1, 0, 0]]

In [99]:
fn = count_model.get_feature_names()
fn

['book', 'cat', 'good', 'shit', 'this']

In [ ]:
l = np.array(Xc.todense()).tolist()
fn = count_model.get_feature_names()
edge_list = list()
for indtop, ro in enumerate(l): 
    #print(ro)
    for ind, col in enumerate(ro):
        # print(col)
        edge_list.append({'source':fn[indtop], 'target': fn[ind], 'weight': col})

In [100]:
edge_list = list()
for indtop, ro in enumerate(l): 
    #print(ro)
    for ind, col in enumerate(ro):
        # print(col)
        edge_list.append({'source':fn[indtop], 'target': fn[ind], 'weight': col})

In [101]:
edge_list

[{'source': 'book', 'target': 'book', 'weight': 0},
 {'source': 'book', 'target': 'cat', 'weight': 0},
 {'source': 'book', 'target': 'good', 'weight': 0},
 {'source': 'book', 'target': 'shit', 'weight': 0},
 {'source': 'book', 'target': 'this', 'weight': 3},
 {'source': 'cat', 'target': 'book', 'weight': 0},
 {'source': 'cat', 'target': 'cat', 'weight': 0},
 {'source': 'cat', 'target': 'good', 'weight': 2},
 {'source': 'cat', 'target': 'shit', 'weight': 1},
 {'source': 'cat', 'target': 'this', 'weight': 1},
 {'source': 'good', 'target': 'book', 'weight': 0},
 {'source': 'good', 'target': 'cat', 'weight': 2},
 {'source': 'good', 'target': 'good', 'weight': 0},
 {'source': 'good', 'target': 'shit', 'weight': 1},
 {'source': 'good', 'target': 'this', 'weight': 1},
 {'source': 'shit', 'target': 'book', 'weight': 0},
 {'source': 'shit', 'target': 'cat', 'weight': 1},
 {'source': 'shit', 'target': 'good', 'weight': 1},
 {'source': 'shit', 'target': 'shit', 'weight': 0},
 {'source': 'shit', '

In [11]:
count_model.vocabulary_

{'this': 4, 'book': 0, 'cat': 1, 'good': 2, 'shit': 3}

In [14]:
count_model = CountVectorizer(ngram_range=(1,1))

In [15]:
count_model.vocabulary_

AttributeError: 'CountVectorizer' object has no attribute 'vocabulary_'

In [9]:
def lemmatizer(text):        
    sent = []
    doc = nlp(" ".join(text))
    for word in doc:
        sent.append(word.lemma_)
    return sent

In [51]:
word_map = set()
for sentence in sents:
    for word in sentence:
        # print(word)
        word = clean_text(word)
        # print(word)
        if word != None and len(word) > 2:
            word_map.add(word)

In [111]:
norm_sents = list()
for sentence in sents:
    st_senten = []
    for word in sentence:
        word = clean_text(word)
        if word != None and len(word) > 2:
            st_senten.append(word)
    norm_sents.append(' '.join(st_senten))

In [112]:
norm_sents[0]

'fulton county grand jury said friday investigation atlantas recent primary election produced evidence irregularities took place'

In [113]:
count_model = CountVectorizer(ngram_range=(1,1), stop_words=STOPWORDS)
X = count_model.fit_transform(norm_sents)
# count_model.vocabulary_
# X[X > 0] = 1 # run this line if you don't want extra within-text cooccurence (see below)
Xc = (X.T * X) # this is co-occurrence matrix in sparse csr format
Xc.setdiag(0) # sometimes you want to fill same word cooccurence to 0
print(Xc.todense()) # print out matrix in dense format
print(count_model.get_feature_names())

[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['accepted', 'achieve', 'act', 'administration', 'administrators', 'allen', 'also', 'ambiguous', 'among', 'appointment', 'appraisers', 'assistance', 'atlanta', 'atlantas', 'automobile', 'available', 'awarding', 'believes', 'best', 'burden', 'charge', 'charged', 'child', 'city', 'clerical', 'combined', 'commented', 'committee', 'compensation', 'conducted', 'considering', 'continue', 'cost', 'counties', 'county', 'court', 'date', 'department', 'departments', 'deserves', 'disable', 'disproportionate', 'distribute', 'distribution', 'durwood', 'effected', 'effective', 'efficiency', 'election', 'enabling', 'end', 'evidence', 'exception', 'executive', 'experienced', 'failure', 'federal', 'feel', 'fees', 'find', 'fire', 'fit', 'follow', 'foster', 'friday', 'fulton', 'funds', 'future', 'general', 'generally', 'georgias', 'governments', 'grand', 'granted', 'greater', 'guardians

In [114]:
Xc.shape

(180, 180)

In [115]:
idis = pd.DataFrame(count_model.get_feature_names())
idis.columns = ['id']
idis.head()

id
0        accepted
1         achieve
2             act
3  administration
4  administrators

In [116]:
idis.to_csv('nodelist.csv', index=False)

In [117]:
idisr = pd.read_csv('nodelist.csv')
idisr.shape

(180, 1)

In [118]:
l = np.array(Xc.todense()).tolist()
fn = count_model.get_feature_names()
edge_list = list()
for indtop, ro in enumerate(l): 
    #print(ro)
    for ind, col in enumerate(ro):
        # print(col)
        edge_list.append({'source':fn[indtop], 'target': fn[ind], 'weight': col})

In [119]:
edgeLdf = pd.DataFrame(edge_list)
edgeLdf

source          target  weight
0        accepted        accepted       0
1        accepted         achieve       0
2        accepted             act       0
3        accepted  administration       0
4        accepted  administrators       0
...           ...             ...     ...
32395  widespread          voters       1
32396  widespread           wards       0
32397  widespread         welfare       0
32398  widespread            well       0
32399  widespread      widespread       0

[32400 rows x 3 columns]

In [120]:
edgeLdf.to_csv('edgelist.csv', index=False)

In [121]:
edgeLdf_r = pd.read_csv('edgelist.csv')
edgeLdf_r.head()

source          target  weight
0  accepted        accepted       0
1  accepted         achieve       0
2  accepted             act       0
3  accepted  administration       0
4  accepted  administrators       0

In [73]:
mdfx = pd.DataFrame(Xc)
mdfx.head()

0
0    (0, 0)\t0\n  (0, 18)\t1\n  (0, 27)\t1\n  (0,...
1    (0, 1)\t0\n  (0, 29)\t1\n  (0, 50)\t1\n  (0,...
2    (0, 2)\t0\n  (0, 7)\t1\n  (0, 40)\t1\n  (0, ...
3    (0, 3)\t0\n  (0, 109)\t1\n  (0, 140)\t1\n  (...
4    (0, 4)\t0\n  (0, 20)\t1\n  (0, 70)\t1\n  (0,...

In [70]:
mdf = pd.DataFrame(Xc.todense())
mdf.head()

0    1    2    3    4    5    6    7    8    9    ...  375  376  377  378  \
0    0    0    0    0    0    0    0    0    0    0  ...    1    0    0    0   
1    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2    0    0    0    0    0    0    0    1    0    0  ...    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   379  380  381  382  383  384  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 385 columns]

In [71]:
mdf.describe()

0           1           2           3           4           5    \
count  385.000000  385.000000  385.000000  385.000000  385.000000  385.000000   
mean     0.054545    0.020779    0.031169    0.023377    0.038961    0.080519   
std      0.227386    0.142830    0.174000    0.151293    0.193754    0.281846   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    2.000000   

              6           7           8           9    ...         375  \
count  385.000000  385.000000  385.000000  385.000000  ...  385.000000   
mean     0.038961    0.080519    0.036364    0.028571  ...    0.054545   
std      0.218991    0.299756    0.187437    0.181757  ...    0.227386   
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
25%      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
50%      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
75%      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
max      2.000000    2.000000    1.000000    2.000000  ...    1.000000   

              376         377         378         379         380         381  \
count  385.000000  385.000000  385.000000  385.000000  385.000000  385.000000   
mean     0.025974    0.033766    0.051948    0.015584    0.049351    0.033766   
std      0.159265    0.180862    0.233637    0.124022    0.228573    0.194729   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
max      1.000000    1.000000    2.000000    1.000000    2.000000    2.000000   

              382         383         384  
count  385.000000  385.000000  385.000000  
mean     0.038961    0.075325    0.018182  
std      0.206758    0.273935    0.133782  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000  
75%      0.000000    0.000000    0.000000  
max      2.000000    2.000000    1.000000  

[8 rows x 385 columns]

In [22]:
bs = str()
for word in word_map:
    bs += f'{word} '
bs

'fire fact outright event ambiguous didnt investigate size surveillance good operation orderly charged former effective support assistance promise recommended hold problem pearl offer mac employed obtain highway atlanta top making bankers laws bellwood force intends juries give property calmest might prices chairman house congressmen offices compensation sen upon warned learned health operating dispute takes time topics something management rescind details precincts courts permit well asked constitutional reasonable old death gubernatorial formally jail trouble generally candidates present jackson receives quickie nevertheless receive jan privilege hurdle encouragement remedy georgia savannah adamant specifically every contracts board gainesville welfare efficiency alpharetta association bowden jury bond friday modernizing would leading office steps night enabling according deputies quiet post authorities general next allowances governments polls allow whether received wednesday act in

In [61]:
edge_dict = dict()
for sentence in sents[:1]:
    for word in sentence:
        # print(word)
        for word_fd in word_map:
            if word_fd in sentence and word in word_map:
                # print(word, word_fd)
                # print(type(edge_dict.get(word, set())))
                pr = edge_dict.get(word, set())
                # print(type(pr))
                pr.add(word_fd)
                # print(pr)
                edge_dict[word] = pr
                # edge_dict.get(word, {'source': word, 'target': word_fd, 'weight': 1})
                # print(edge_dict.get(word, {'source': word, 'target': word_fd, 'weight': 0}))
                # edge_dict[].append({'source': word, 'target': word_fd}) 

In [62]:
edge_dict

{'said': {'election',
  'evidence',
  'investigation',
  'irregularities',
  'place',
  'primary',
  'produced',
  'recent',
  'said',
  'took'},
 'investigation': {'election',
  'evidence',
  'investigation',
  'irregularities',
  'place',
  'primary',
  'produced',
  'recent',
  'said',
  'took'},
 'recent': {'election',
  'evidence',
  'investigation',
  'irregularities',
  'place',
  'primary',
  'produced',
  'recent',
  'said',
  'took'},
 'primary': {'election',
  'evidence',
  'investigation',
  'irregularities',
  'place',
  'primary',
  'produced',
  'recent',
  'said',
  'took'},
 'election': {'election',
  'evidence',
  'investigation',
  'irregularities',
  'place',
  'primary',
  'produced',
  'recent',
  'said',
  'took'},
 'produced': {'election',
  'evidence',
  'investigation',
  'irregularities',
  'place',
  'primary',
  'produced',
  'recent',
  'said',
  'took'},
 'evidence': {'election',
  'evidence',
  'investigation',
  'irregularities',
  'place',
  'primary',